# Travis CI (https://travis-ci.org/dubreuia/intellij-plugin-save-actions)

dist: bionic

language: java

jdk:
    - oraclejdk11

script:
    - cd exercices/exercism-darts && ./gradlew test && cd ../../
    - cd exercices/exercism-rna-transcription && ./gradlew test && cd ../../
    - cd exercices/exercism-two-fer && ./gradlew test && cd ../../
    - cd exercices/exercism-yacht && ./gradlew test && cd ../../

branches:
    only:
        - /.*/

notifications:
    email: true
